### ISSUE TITLE
Disable chat spam please

### ISSUE THREAD

**Issue by Fixided** [Forecaster/runUp#1]
The chat keeps spamming setting RunUp Height: 1/ 0.5

**Comment by Forecaster** [comment]
If you are using version 1.0 download 1.1 instead.

I uploaded that specifically to remove the spam.

**Comment by Fixided** [comment]
I am using 1.1
It's the only 1.7.10 version of the mod.

**Comment by Forecaster** [comment]
Oh right, I never updated it because I broke something. I intended to upload a version with the chat messages disabled...

**Comment by Forecaster** [comment]
Fixed by 76da8c4d21f01f562c4e04decdb3570fcc634184

After this commit version 1.1.1 was built.
Download once approved: http://minecraft.curseforge.com/mc-mods/70983-runup/files/2215820
